/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Logica.Idioma;
import Logica.Registros;
import Logica.Usuarios;
import java.awt.Color;

/**
 *
 * @author Jhonatan Schneider
 * 
 * Ventana del menu de opciones que dispone el usuario para realizar en el cajero
 */
public class Menu extends javax.swing.JFrame {

    String ruta = "C:\\Archivos gestor\\Cuentas\\";
    String cuenta ;
    
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        Idioma I = new Idioma();
        Usuarios u = new Usuarios();
        ruta = "C:\\Archivos gestor\\Cuentas\\" + u.IdCuenta();
        String direccion = "C:\\Archivos gestor\\Idiomas\\" + I.leerFila(1,"C:\\Archivos gestor\\Idiomas\\Estado.txt");
        Salir.setText(I.leerFila(13,direccion));
        Titulo.setText(I.leerFila(41,direccion));
        deposito.setText(I.leerFila(42,direccion));
        retiro.setText(I.leerFila(43,direccion));
        servicio.setText(I.leerFila(44,direccion));
        cambioPin.setText(I.leerFila(45,direccion));
        consultaSaldo.setText(I.leerFila(46,direccion));
        extracto.setText(I.leerFila(47,direccion));
        transferencia.setText(I.leerFila(48,direccion));
        otros.setText(I.leerFila(49,direccion));
        u.llenarComboBoxConArchivos(Cuentas, ruta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Panel1 = new javax.swing.JPanel();
        deposito = new javax.swing.JLabel();
        Panel2 = new javax.swing.JPanel();
        retiro = new javax.swing.JLabel();
        Panel3 = new javax.swing.JPanel();
        servicio = new javax.swing.JLabel();
        Panel4 = new javax.swing.JPanel();
        cambioPin = new javax.swing.JLabel();
        Panel5 = new javax.swing.JPanel();
        consultaSaldo = new javax.swing.JLabel();
        Panel6 = new javax.swing.JPanel();
        extracto = new javax.swing.JLabel();
        Panel8 = new javax.swing.JPanel();
        otros = new javax.swing.JLabel();
        Panel7 = new javax.swing.JPanel();
        transferencia = new javax.swing.JLabel();
        Panel04 = new javax.swing.JPanel();
        Salir = new javax.swing.JLabel();
        Cuentas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(21, 239, 82));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 675));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Seleccione el servicio deseado");
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1200, -1));

        Panel1.setBackground(new java.awt.Color(0, 205, 57));

        deposito.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        deposito.setForeground(new java.awt.Color(255, 255, 255));
        deposito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deposito.setText("Deposito");
        deposito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deposito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depositoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                depositoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                depositoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deposito, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deposito, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel1.add(Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 350, 70));

        Panel2.setBackground(new java.awt.Color(0, 205, 57));

        retiro.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        retiro.setForeground(new java.awt.Color(255, 255, 255));
        retiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        retiro.setText("Retiro");
        retiro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        retiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retiroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                retiroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                retiroMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(retiro, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(retiro, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel1.add(Panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 350, 70));

        Panel3.setBackground(new java.awt.Color(0, 205, 57));

        servicio.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        servicio.setForeground(new java.awt.Color(255, 255, 255));
        servicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        servicio.setText("Servicios");
        servicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        servicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                servicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                servicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                servicioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel3Layout = new javax.swing.GroupLayout(Panel3);
        Panel3.setLayout(Panel3Layout);
        Panel3Layout.setHorizontalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(servicio, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        Panel3Layout.setVerticalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(servicio, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel1.add(Panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 350, -1));

        Panel4.setBackground(new java.awt.Color(0, 205, 57));

        cambioPin.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        cambioPin.setForeground(new java.awt.Color(255, 255, 255));
        cambioPin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cambioPin.setText("Cambio de pin");
        cambioPin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cambioPin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cambioPinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cambioPinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cambioPinMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel4Layout = new javax.swing.GroupLayout(Panel4);
        Panel4.setLayout(Panel4Layout);
        Panel4Layout.setHorizontalGroup(
            Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cambioPin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        Panel4Layout.setVerticalGroup(
            Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cambioPin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel1.add(Panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, -1));

        Panel5.setBackground(new java.awt.Color(0, 205, 57));

        consultaSaldo.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        consultaSaldo.setForeground(new java.awt.Color(255, 255, 255));
        consultaSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        consultaSaldo.setText("Consulta de saldo");
        consultaSaldo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultaSaldo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                consultaSaldoMouseDragged(evt);
            }
        });
        consultaSaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultaSaldoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                consultaSaldoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                consultaSaldoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel5Layout = new javax.swing.GroupLayout(Panel5);
        Panel5.setLayout(Panel5Layout);
        Panel5Layout.setHorizontalGroup(
            Panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(consultaSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel5Layout.setVerticalGroup(
            Panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(consultaSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(Panel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 350, 70));

        Panel6.setBackground(new java.awt.Color(0, 205, 57));

        extracto.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        extracto.setForeground(new java.awt.Color(255, 255, 255));
        extracto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        extracto.setText("Extracto");
        extracto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        extracto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                extractoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                extractoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                extractoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel6Layout = new javax.swing.GroupLayout(Panel6);
        Panel6.setLayout(Panel6Layout);
        Panel6Layout.setHorizontalGroup(
            Panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(extracto, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        Panel6Layout.setVerticalGroup(
            Panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(extracto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel1.add(Panel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 350, -1));

        Panel8.setBackground(new java.awt.Color(0, 205, 57));

        otros.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        otros.setForeground(new java.awt.Color(255, 255, 255));
        otros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        otros.setText("Otros");
        otros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        otros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                otrosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                otrosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                otrosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel8Layout = new javax.swing.GroupLayout(Panel8);
        Panel8.setLayout(Panel8Layout);
        Panel8Layout.setHorizontalGroup(
            Panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(otros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        Panel8Layout.setVerticalGroup(
            Panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(otros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel1.add(Panel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, -1, -1));

        Panel7.setBackground(new java.awt.Color(0, 205, 57));

        transferencia.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        transferencia.setForeground(new java.awt.Color(255, 255, 255));
        transferencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transferencia.setText("Transferencia");
        transferencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transferencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transferenciaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transferenciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transferenciaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel7Layout = new javax.swing.GroupLayout(Panel7);
        Panel7.setLayout(Panel7Layout);
        Panel7Layout.setHorizontalGroup(
            Panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transferencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        Panel7Layout.setVerticalGroup(
            Panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transferencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel1.add(Panel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, -1, -1));

        Panel04.setBackground(new java.awt.Color(115, 115, 115));

        Salir.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Salir.setText("Salir");
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel04Layout = new javax.swing.GroupLayout(Panel04);
        Panel04.setLayout(Panel04Layout);
        Panel04Layout.setHorizontalGroup(
            Panel04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel04Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel04Layout.setVerticalGroup(
            Panel04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel04Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(Panel04, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 570, 240, 60));

        Cuentas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CuentasItemStateChanged(evt);
            }
        });
        Cuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentasActionPerformed(evt);
            }
        });
        jPanel1.add(Cuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 240, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void depositoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositoMouseEntered
        Panel1.setBackground(new Color(0,139,43));
    }//GEN-LAST:event_depositoMouseEntered

    private void retiroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retiroMouseEntered
        Panel2.setBackground(new Color(0,139,43));
    }//GEN-LAST:event_retiroMouseEntered

    private void servicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servicioMouseEntered
        Panel3.setBackground(new Color(0,139,43));
    }//GEN-LAST:event_servicioMouseEntered

    private void cambioPinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cambioPinMouseEntered
        Panel4.setBackground(new Color(0,139,43));
    }//GEN-LAST:event_cambioPinMouseEntered

    private void consultaSaldoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaSaldoMouseEntered
        Panel5.setBackground(new Color(0,139,43));
    }//GEN-LAST:event_consultaSaldoMouseEntered

    private void extractoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extractoMouseEntered
        Panel6.setBackground(new Color(0,139,43));
    }//GEN-LAST:event_extractoMouseEntered

    private void transferenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferenciaMouseEntered
        Panel7.setBackground(new Color(0,139,43));
    }//GEN-LAST:event_transferenciaMouseEntered

    private void otrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_otrosMouseEntered
        Panel8.setBackground(new Color(0,139,43));
    }//GEN-LAST:event_otrosMouseEntered

    private void depositoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositoMouseExited
        Panel1.setBackground(new Color(0,205,57));
    }//GEN-LAST:event_depositoMouseExited

    private void retiroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retiroMouseExited
        Panel2.setBackground(new Color(0,205,57));
    }//GEN-LAST:event_retiroMouseExited

    private void servicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servicioMouseExited
        Panel3.setBackground(new Color(0,205,57));
    }//GEN-LAST:event_servicioMouseExited

    private void cambioPinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cambioPinMouseExited
        Panel4.setBackground(new Color(0,205,57));
    }//GEN-LAST:event_cambioPinMouseExited

    private void consultaSaldoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaSaldoMouseExited
        Panel5.setBackground(new Color(0,205,57));
    }//GEN-LAST:event_consultaSaldoMouseExited

    private void extractoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extractoMouseExited
        Panel6.setBackground(new Color(0,205,57));
    }//GEN-LAST:event_extractoMouseExited

    private void transferenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferenciaMouseExited
        Panel7.setBackground(new Color(0,205,57));
    }//GEN-LAST:event_transferenciaMouseExited

    private void otrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_otrosMouseExited
        Panel8.setBackground(new Color(0,205,57));
    }//GEN-LAST:event_otrosMouseExited

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        Inicio a = new Inicio();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_SalirMouseClicked

    private void SalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseEntered
        Panel04.setBackground(new Color(70,70,70));
    }//GEN-LAST:event_SalirMouseEntered

    private void SalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseExited
        Panel04.setBackground(new Color(115,115,115));
    }//GEN-LAST:event_SalirMouseExited

    private void depositoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositoMouseClicked
        Usuarios u = new Usuarios();
        String rutaCuenta = "C:\\Archivos gestor\\Cuentas\\" + u.IdCuenta() + "\\"+u.obtenerRuta((String) Cuentas.getSelectedItem());
        u.guardarRutaEnArchivo(rutaCuenta);
        Deposito a = new Deposito();
        a.setMenu(this);
        a.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_depositoMouseClicked

    private void retiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retiroMouseClicked
        Usuarios u = new Usuarios();
        String rutaCuenta = "C:\\Archivos gestor\\Cuentas\\" + u.IdCuenta() + "\\"+u.obtenerRuta((String) Cuentas.getSelectedItem());
        u.guardarRutaEnArchivo(rutaCuenta);
        CantidadRetiro a = new CantidadRetiro();
        a.setMenu(this);
        a.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_retiroMouseClicked

    private void servicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servicioMouseClicked
        Servic a = new Servic();
        a.setVisible(true);
        a.setMenu(this);
         this.setVisible(false);
    }//GEN-LAST:event_servicioMouseClicked

    private void cambioPinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cambioPinMouseClicked
        CambioPin a = new CambioPin();
        a.setMenu(this);
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cambioPinMouseClicked

    private void consultaSaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaSaldoMouseClicked
        Usuarios u = new Usuarios();
        String rutaCuenta = "C:\\Archivos gestor\\Cuentas\\" + u.IdCuenta() + "\\"+u.obtenerRuta(cuenta);
        u.guardarRutaEnArchivo(rutaCuenta);
        DetallesSaldo a = new DetallesSaldo();
        a.setMenu(this);
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_consultaSaldoMouseClicked
   
    private void extractoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extractoMouseClicked
        Usuarios u = new Usuarios();
        String rutaCuenta = "C:\\Archivos gestor\\Cuentas\\" + u.IdCuenta() + "\\"+u.obtenerRuta((String) Cuentas.getSelectedItem());
        u.guardarRutaEnArchivo(rutaCuenta);
        Extracto a = new Extracto();
        a.setMenu(this);
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_extractoMouseClicked

    private void transferenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferenciaMouseClicked
        Usuarios u = new Usuarios();
        String rutaCuenta = "C:\\Archivos gestor\\Cuentas\\" + u.IdCuenta() + "\\"+u.obtenerRuta((String) Cuentas.getSelectedItem());
        u.guardarRutaEnArchivo(rutaCuenta);
        transferencia a = new transferencia();
        a.setMenu(this);
        a.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_transferenciaMouseClicked

    private void otrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_otrosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_otrosMouseClicked

    private void consultaSaldoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaSaldoMouseDragged
        
    }//GEN-LAST:event_consultaSaldoMouseDragged

    private void CuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentasActionPerformed

    private void CuentasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CuentasItemStateChanged
        // TODO add your handling code here:
        cuenta = (String) Cuentas.getSelectedItem();
    }//GEN-LAST:event_CuentasItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cuentas;
    private javax.swing.JPanel Panel04;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel3;
    private javax.swing.JPanel Panel4;
    private javax.swing.JPanel Panel5;
    private javax.swing.JPanel Panel6;
    private javax.swing.JPanel Panel7;
    private javax.swing.JPanel Panel8;
    private javax.swing.JLabel Salir;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel cambioPin;
    private javax.swing.JLabel consultaSaldo;
    private javax.swing.JLabel deposito;
    private javax.swing.JLabel extracto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel otros;
    private javax.swing.JLabel retiro;
    private javax.swing.JLabel servicio;
    private javax.swing.JLabel transferencia;
    // End of variables declaration//GEN-END:variables
}
