/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Logica.Idioma;
import Logica.Operaciones;
import Logica.Registros;
import Logica.Usuarios;
import java.awt.Color;
import java.io.File;

/**
 *
 * @author Jhonatan Schneider
 * 
 * Ventana que muestra el total de dinero ingresado para el tema de los depositos
 */

public class TotalDeposito extends javax.swing.JFrame {

    private String totalDeposito;
    private String tipo;
    private String nro;
    private Menu m;
    public TotalDeposito() {
        initComponents();
        this.setLocationRelativeTo(null);
        Idioma I = new Idioma();
        String direccion = "C:\\Archivos gestor\\Idiomas\\" + I.leerFila(1,"C:\\Archivos gestor\\Idiomas\\Estado.txt");
        SubTitulo1.setText(I.leerFila(59,direccion));
        SubTitulo2.setText(I.leerFila(60,direccion));
        Cant.setText(I.leerFila(61,direccion)+":");
        Mensaje.setText(I.leerFila(62,direccion));
        Boton1.setText(I.leerFila(63,direccion));
        Boton2.setText(I.leerFila(64,direccion));
    }
    
    
   public void setTipo(String tipo, String nro){
        this.tipo = tipo;
        this.nro = nro;
    }
    public void setTotalDeposito(String totalDeposito){
        Operaciones o = new Operaciones();
        Usuarios u = new Usuarios();
        monto.setText(totalDeposito);
        cambio.setText(o.MonedaCuenta(u.rutaCuenta()));
    }
    
    public void setMenu(Menu m){
        this.m = m;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SubTitulo2 = new javax.swing.JLabel();
        SubTitulo1 = new javax.swing.JLabel();
        Panel3 = new javax.swing.JPanel();
        Boton2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Panel02 = new javax.swing.JPanel();
        Boton1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Mensaje = new javax.swing.JLabel();
        Cant = new javax.swing.JLabel();
        monto = new javax.swing.JLabel();
        cambio = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(21, 239, 82));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SubTitulo2.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        SubTitulo2.setForeground(new java.awt.Color(255, 255, 255));
        SubTitulo2.setText("hasta el momento");
        jPanel1.add(SubTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 770, 70));

        SubTitulo1.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        SubTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        SubTitulo1.setText("Total ingresado ");
        jPanel1.add(SubTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 740, 70));

        Panel3.setBackground(new java.awt.Color(243, 214, 76));

        Boton2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        Boton2.setForeground(new java.awt.Color(255, 255, 255));
        Boton2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Boton2.setText("Confirmar");
        Boton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel3Layout = new javax.swing.GroupLayout(Panel3);
        Panel3.setLayout(Panel3Layout);
        Panel3Layout.setHorizontalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Boton2, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        Panel3Layout.setVerticalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(Panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 540, 240, 70));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Diseño sin título (1).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-250, 170, 510, 510));

        Panel02.setBackground(new java.awt.Color(243, 214, 76));

        Boton1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        Boton1.setForeground(new java.awt.Color(255, 255, 255));
        Boton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Boton1.setText("Agregar mas");
        Boton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel02Layout = new javax.swing.GroupLayout(Panel02);
        Panel02.setLayout(Panel02Layout);
        Panel02Layout.setHorizontalGroup(
            Panel02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel02Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel02Layout.setVerticalGroup(
            Panel02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel02Layout.createSequentialGroup()
                .addComponent(Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel1.add(Panel02, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 240, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Diseño sin título (1).png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, -240, 350, 540));

        Mensaje.setBackground(new java.awt.Color(21, 239, 82));
        Mensaje.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        Mensaje.setForeground(new java.awt.Color(255, 255, 255));
        Mensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mensaje.setText("¿Esto es correcto?");
        jPanel1.add(Mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 1200, 60));

        Cant.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        Cant.setForeground(new java.awt.Color(255, 255, 255));
        Cant.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Cant.setText("Cantidad");
        jPanel1.add(Cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 200, 50));

        monto.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        monto.setForeground(new java.awt.Color(255, 255, 255));
        monto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        monto.setText("10000");
        jPanel1.add(monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 330, 190, 50));

        cambio.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        cambio.setForeground(new java.awt.Color(255, 255, 255));
        cambio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cambio.setText("USD.");
        jPanel1.add(cambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 330, 90, 50));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("__________________");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 370, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton2MouseClicked
        if(tipo=="1"){
            Operaciones o = new Operaciones();
            Registros r = new Registros();
            Usuarios u = new Usuarios();
            File archivoCuenta = o.buscarArchivoPorNumeroCuenta(nro);
                String ruta = archivoCuenta.getAbsolutePath();
                double SaldoActual = Double.parseDouble(o.SaldoActual(ruta));
                double nuevoSaldo;
                nuevoSaldo = SaldoActual + Double.parseDouble(monto.getText());
                r.guardarRegistroOperaciones("+"+monto.getText(), u.IdTransferenci(ruta), 1, ruta);
                o.modificarSaldo(ruta, Double.toString(nuevoSaldo));
                System.out.println("Se encontró el archivo de cuenta: " + nuevoSaldo);
                ConfirmDeposito p = new ConfirmDeposito();
                p.setMenu(m);
                p.setVisible(true);
                this.dispose();
        }else{    
            Operaciones o = new Operaciones();
            Registros r = new Registros();
            Usuarios u = new Usuarios();
            String id = u.IdCuenta();
            String ruta = u.rutaCuenta();
            double SaldoActual = Double.parseDouble(o.SaldoActual(ruta));
            double montodeposito = Double.parseDouble(monto.getText());
            double nuevoSaldo;
            nuevoSaldo = SaldoActual + montodeposito;
            o.modificarSaldo(ruta, Double.toString(nuevoSaldo));
            r.guardarRegistroOperaciones("+ "+monto.getText(), id, 1, ruta);
            ConfirmDeposito a = new ConfirmDeposito();
            a.setMenu(m);
            a.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_Boton2MouseClicked

    private void Boton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton2MouseEntered
        Panel3.setBackground(new Color(210,180,23));
    }//GEN-LAST:event_Boton2MouseEntered

    private void Boton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton2MouseExited
        Panel3.setBackground(new Color(243,214,76));
    }//GEN-LAST:event_Boton2MouseExited

    private void Boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton1MouseClicked
        CantidadDeposito a = new CantidadDeposito();
        a.setMenu(m);
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_Boton1MouseClicked

    private void Boton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton1MouseEntered
        Panel02.setBackground(new Color(210,180,23));
    }//GEN-LAST:event_Boton1MouseEntered

    private void Boton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton1MouseExited
        Panel02.setBackground(new Color(243,214,76));
    }//GEN-LAST:event_Boton1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TotalDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TotalDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TotalDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TotalDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TotalDeposito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Boton1;
    private javax.swing.JLabel Boton2;
    private javax.swing.JLabel Cant;
    private javax.swing.JLabel Mensaje;
    private javax.swing.JPanel Panel02;
    private javax.swing.JPanel Panel3;
    private javax.swing.JLabel SubTitulo1;
    private javax.swing.JLabel SubTitulo2;
    private javax.swing.JLabel cambio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel monto;
    // End of variables declaration//GEN-END:variables
}
